apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
  labels:
    app: health-alternator
spec:
  replicas: 1
  selector:
    matchLabels:
      service: microservice2
  template:
    metadata:
      labels:
        app: health-alternator
        service: microservice2
    spec:
      containers:
        - name: microservice2
          image: tjdockeracr.azurecr.io/microservice2:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: microservice2
  labels:
    app: health-alternator
    service: microservice2
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: microservice2