apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverstatusservice
  labels:
    app: health-alternator
spec:
  replicas: 1
  selector:
    matchLabels:
      service: serverstatusservice
  template:
    metadata:
      labels:
        app: health-alternator
        service: serverstatusservice
    spec:
      containers:
        - name: serverstatusservice
          image: tjdockeracr.azurecr.io/serverstatusservice:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: serverstatusservice
  labels:
    app: health-alternator
    service: serverstatusservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: serverstatusservice